[[redirects]]
  from = "/regioni"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/italia"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/grafici"
  to = "/index.html"
  status = 200